"""Add data_volume default

Revision ID: 213eb3b5976c
Revises: 718d2640dde6
Create Date: 2025-12-09 15:20:38.003774

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "213eb3b5976c"
down_revision: Union[str, Sequence[str], None] = "718d2640dde6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("username", sa.VARCHAR(), nullable=False),
        sa.Column("password", sa.VARCHAR(), nullable=False),
        sa.Column("ip", sa.VARCHAR(), nullable=True),
        sa.Column("data_volume", sa.INTEGER(), nullable=True),
        sa.Column("data_volume_limit", sa.INTEGER(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###
