"""Update User

Revision ID: ebe129943722
Revises: 213eb3b5976c
Create Date: 2025-12-09 15:37:21.101148

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ebe129943722"
down_revision: Union[str, Sequence[str], None] = "213eb3b5976c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("username", sa.VARCHAR(), nullable=False),
        sa.Column("password", sa.VARCHAR(), nullable=False),
        sa.Column("ip", sa.VARCHAR(), nullable=True),
        sa.Column("data_volume", sa.INTEGER(), nullable=False),
        sa.Column("data_volume_limit", sa.INTEGER(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###
